import type { Metadata } from "next";
import { JetBrains_Mono, Inter, Courier_Prime } from "next/font/google";
import "./globals.css";
import React, {ReactNode} from "react";

import Header from "./components/Header";
import { PageTransitionProvider } from "./components/PageTransitionProvider";

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-jetbrainsMono',
});

const inter = Inter({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-inter',
});

const courierPrime = Courier_Prime({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: '--font-courier',
});

export const metadata: Metadata = {
  title: "Natalie's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${jetbrainsMono.variable} ${inter.variable} ${courierPrime.variable} antialiased bg-primary text-white leading-relaxed font-primary`}>
        <PageTransitionProvider>
          <div className="mx-auto max-w-[1024px] w-full px-6 md:px-12 min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow flex flex-col justify-center">
              {children}
            </main>
          </div>
        </PageTransitionProvider>
    </body>
    </html>
  );
}
